### PR TITLE
nga_parallaxMotionEffectGroup getter responsible for instantiation

### PR DESCRIPTION
**Pull request by zmcartor**
Hello, this is a great category, thanks for releasing :smile_cat: 

I thought it would be cleaner if the getter function was responsible for ensuring a valid UIMotionEffectGroup is returned. Open to feedback if this pull req doesn't meet your standards.

### CODE REVIEW

**Comment by michaeljbishop** [comment]
At the moment, the `nga_parallaxMotionEffectGroup` method-pair is supposed to be a lightweight implementation of essentially the `@property` syntax but wired to the associated object facility. I'm interested in this idea of this PR, but am worried that calling:

```
[self nga_setParallaxMotionEffectGroup:nil];
assert([self nga_parallaxMotionEffectGroup] == nil);
```

would fail the expectations of the user.

I'm not against lazy-loading properties in principle, but I prefer them on read-only properties.

However, if I have misread your intent, please set me straight :) Glad you are finding use for this category.

**Comment by zmcartor** [comment]
Hello,

Is the motivation to have `kNGAParallaxMotionEffectGroupKey` available to the category including class ?

The way `kNGAParallaxMotionEffectGroupKey` is used, appears like a private category variable than a shared class level variable. (The docs don't mention it, only `@property parallaxIntensity`) If this variable is not exposed to the category including class , the problem of 

`[self nga_setParallaxMotionEffectGroup:nil];` 

would not occur.

**Comment by michaeljbishop** [comment]
It's true, those are not public methods so this would not change the contract of the public api. However, here's a better example of what I'm trying to get at.

In the call `setParallaxIntensity:`, I only want to call `addMotionEffect:` when I've created a new `UIMotionEffectGroup`. I want those two things to be paired. I don't want to add the motion effect more than once if it's already been added. However, at that level of the code, you can't tell if you are creating a new `UIMotionEffectGroup` because it's been hidden in the lazy-loading of the `nga_parallaxMotionEffectGroup` call.

You could fix this by moving the `addMotionEffect:` call into the implementation of `nga_parallaxMotionEffectGroup`, but at that point, you'd be calling `[self nga_parallaxMotionEffectGroup]` inside `setParallaxIntensity:` for the side-effect that it calls `addMotionEffect:`.

This is an example of why I prefer keeping these objc_get/setAssociatedObject wrappers simple and treating them like an api internal to the class.

**Comment by zmcartor** [comment]
That makes sense. repeatedly adding `UIMotionEffectGroup` each time `setParallaxIntensity` is not good side effect.

Thanks for the discussion! :crescent_moon:

**Comment by michaeljbishop** [comment]
No problem. Thanks for making me think :)

**Pull request closed without merging**
